feat: add digest authentication
superfaceai/docs pull request #59
Opened 2022-01-24 06:43 UTC by Jakub-Vacek

This PR adds basic description of Digest Auth in provider.json. Waiting on actually released digest in sdk.

2022-01-24 10:23 UTC, kysely reviewed
👍 I honestly don't have any comments that would improve your work here.

Just a reminder we have this information in other places in docs so it might be worth updating those, too:
- [Reference/Super.json](https://superface.ai/docs/reference/superjson#securityvalues)
- [Comlink/Reference/Provider](https://superface.ai/docs/comlink/reference/provider#security-scheme)

2022-01-24 10:23 UTC, kysely commented on docs/guides/add-new-provider.md
> +_`Authorization: Digest <credentials>` in headers_
```suggestion
_e.g. `Authorization: Digest <credentials>` in headers_
```

2022-02-14 13:25 UTC, jnv commented
@Jakub-Vacek What is the status, has this been released?

2022-02-15 07:10 UTC, Jakub-Vacek commented
It hasn't 😒 We have it in release candidate `1.3.0-rc.0 `

2022-02-16 06:02 UTC, Jakub-Vacek commented
@jnv Digest in SDK is released (1.3.0), this can be merged.

2022-02-21 08:45 UTC, jnv requested changes

2022-02-21 08:45 UTC, jnv commented on docs/comlink/reference/provider.mdx
> +- `statusCode` (number, optional) - HTTP status code that should be returned from initial call (containing challenge header). Default value is `401`.
I don't quite understand the description, let me try to rephrase it.

```suggestion
- `statusCode` (number, optional) - HTTP status code expected for the initial response with the challenge header. Default value is `401`.
```

2022-02-21 08:45 UTC, jnv commented on docs/comlink/reference/provider.mdx
> +- `challengeHeader` (string, optional) - Case insensitive name of header containing challenge from the server. Default value is `www-authenticate`.
```suggestion
- `challengeHeader` (string, optional) - Case insensitive name of the response header with server issued challenge. Default value is [`www-authenticate`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate).
```

2022-02-21 08:45 UTC, jnv commented on docs/comlink/reference/provider.mdx
> +- `authorizationHeader` (string, optional) - Case insensitive name of header containing authorization. Default value is `Authorization`.
```suggestion
- `authorizationHeader` (string, optional) - Case insensitive name of the request header containing digest authorization details. Default value is [`authorization`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization).
```

2022-02-21 08:45 UTC, jnv commented on docs/guides/add-new-provider.md
> +- `authorizationHeader` Case insensitive name of header containing authorization. Default value is `Authorization`.
I would remove this section and added a link to the relevant reference section instead. I suppose these parameters will be rarely needed.

2022-03-01 14:09 UTC, jnv commented
@Jakub-Vacek Since the feature was released, could you please revise and merge this?

2022-03-25 09:34 UTC, jnv approved these changes
:shipit:

2022-12-30 07:31 UTC, Jakub-Vacek commented
@jnv I am sorry I completely forgot about this PR for some reason 🤦🏻‍♂️😩 I have resolved conflicts and I think it is good to go. Can you please check if it still ok? 🙏

2022-12-30 09:38 UTC, jnv approved these changes
LGTM! :shipit:

2023-01-02 05:54 UTC, merged